### PR TITLE
rename Indonesia to India (bug 1122588)

### PR DESCRIPTION
**Pull request by andymckay**

### CODE REVIEW

**Comment by muffinresearch** [comment]
Lgtm r+

**Comment by ngokevin** [comment]
you'd want to bump the minor version not the patch version next time (so 0.4.0)

**Comment by ngokevin** [comment]
usually prepend commit msg with version #

**Comment by andymckay** [comment]
why 0.4.0 not 0.3.2? and what version number 0.3.2?

**Comment by ngokevin** [comment]
Sorry, I was mistaken. Since this is purely a bug fix, bumping the patch number is correct.

Yeah you'd prepend the commit like "v0.3.1 blah blah".

**Comment by andymckay** [comment]
Ah so you are going for MAJOR.MINOR.PATCH version numbers as per http://semver.org/? Adopting that makes sense to me, been a bit loosey goosey on that in the past.

**Pull request merged**
